@startuml
scale 2
class Event {
    -phone: string
    -initTime: DateTime
    -type: string
    -registration: boolean
    +notifyPerson()
}

class ApplicationUser {
    -phone: string
    -fName: string
    -lName: string
    -street: string
    -strnumber: string
    -city: string
    -changeProfile()
    +setStatus()
    
}

class ApplicationProcessor {
    +openForSpeaking: boolean
    -callForAction()
    +applyAsSpokePerson()
}

class Topic {
    +title: string
    +sourceCodeUrl: string
    +downloadMaterials()
}

class Attendee {
    -eventAttended: number
    -suggestEventBasedOnPreference()
    +registerForTicket()
}

ApplicationUser <|-- ApplicationProcessor
ApplicationUser <|-- Attendee
Speaker "1" *-- "*" Topic
Event "1" o-- "*" Speaker
Event "1" o-- "*" Attendee
@enduml